[package]
name              = "xtask"
version           = "0.1.0"
edition.workspace = true
license           = "GPL-3.0-or-later"
publish.workspace = true

[dependencies]
anyhow.workspace         = true
backtrace.workspace      = true
cargo_metadata.workspace = true
cargo_toml.workspace     = true
clap                     = { workspace = true, features = ["derive"] }
gh-workflow.workspace    = true
indexmap.workspace       = true
indoc.workspace          = true
serde.workspace          = true
serde_json.workspace     = true
toml.workspace           = true
toml_edit.workspace      = true

[lints]
workspace = true
