[package]
name              = "proxy_handshake"
version           = "0.1.0"
edition.workspace = true
description       = "Sans-IO client handshakes for HTTP CONNECT and SOCKS proxies"
license           = "Apache-2.0"
publish.workspace = true

[lib]
doctest = true
path    = "src/proxy_handshake.rs"

[dependencies]
base64.workspace           = true
futures                    = { workspace = true, optional = true }
httparse.workspace         = true
percent-encoding.workspace = true
thiserror.workspace        = true
tokio                      = { workspace = true, features = ["io-util"], optional = true }
url.workspace              = true

[dev-dependencies]
futures.workspace  = true
piper.workspace    = true
proptest.workspace = true
tokio              = { workspace = true, features = ["io-util", "macros", "rt"] }

[features]
default    = []
futures-io = ["dep:futures"]
tokio      = ["dep:tokio"]

[lints]
workspace = true
