# yaml-language-server: $schema=https://cdn.jsdelivr.net/npm/@kjanat/actionlint/actionlint.schema.json
---
self-hosted-runner: null # none, all github actions
assume-default-permissions: permissive

# Disable shellcheck because it doesn't like powershell
# This should have been triggered with initial rollout of actionlint
# but https://github.com/zed-industries/zed/pull/36693
# somehow caused actionlint to actually check those windows jobs
# where previously they were being skipped. Likely caused by an
# unknown bug in actionlint where parsing of `runs-on: [ ]`
# breaks something else. (yuck)
paths: # my workflows end in .yaml on purpose, zed uses .yml
  ".github/workflows/**/*.yml": { ignore: ["shellcheck", "label"] }
