[package]
name              = "gpui_platform"
version           = "0.1.0"
edition.workspace = true
license           = "Apache-2.0"
publish.workspace = true

[lib]
path = "src/gpui_platform.rs"

[dependencies]
gpui.workspace = true

[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
gpui_linux.workspace = true

[target.'cfg(target_family = "wasm")'.dependencies]
console_error_panic_hook.workspace = true
gpui_web.workspace                 = true

[target.'cfg(target_os = "macos")'.dependencies]
gpui_macos.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
gpui                   = { workspace = true, features = ["windows-manifest"] }
gpui_windows.workspace = true

[features]
default         = []
bench-support   = ["gpui_macos/bench-support", "gpui/bench-support"]
font-kit        = ["gpui_macos/font-kit"]
runtime_shaders = ["gpui_macos/runtime_shaders"]
screen-capture  = ["gpui_linux/screen-capture", "gpui_macos/screen-capture", "gpui_windows/screen-capture", "gpui/screen-capture"]
test-support    = ["gpui_macos/test-support", "gpui_windows/test-support", "gpui/test-support"]
wayland         = ["gpui_linux/wayland"]
x11             = ["gpui_linux/x11"]

[lints]
workspace = true
