[package]
name              = "zeta_prompt"
version           = "0.1.0"
edition.workspace = true
license           = "GPL-3.0-or-later"
publish.workspace = true

[lib]
path = "src/zeta_prompt.rs"

[dependencies]
anyhow.workspace = true
serde.workspace  = true
strum.workspace  = true

[dev-dependencies]
indoc.workspace = true

[lints]
workspace = true
