[package]
name              = "assets"
version           = "0.1.0"
edition.workspace = true
license           = "GPL-3.0-or-later"
publish.workspace = true

[lib]
path = "src/assets.rs"

[dependencies]
anyhow.workspace = true
gpui.workspace   = true
util.workspace   = true

[lints]
workspace = true
