[package]
name              = "sum_tree"
version           = "0.1.0"
edition.workspace = true
description       = "A sum tree data structure, a concurrency-friendly B-tree"
license           = "Apache-2.0"
publish           = false

[package.metadata.cargo-shear]
ignored = ["tracing"]

[lib]
doctest = false
path    = "src/sum_tree.rs"

[dependencies]
heapless.workspace = true
log.workspace      = true
proptest           = { workspace = true, optional = true }
rayon.workspace    = true
tracing.workspace  = true
ztracing.workspace = true

[dev-dependencies]
ctor.workspace     = true
proptest.workspace = true
rand.workspace     = true
zlog.workspace     = true

[features]
test-support = ["proptest"]

[lints]
workspace = true
