[package]
name              = "slash_commands_example"
version           = "0.1.0"
edition.workspace = true
license           = "Apache-2.0"
publish.workspace = true

[lib]
crate-type = ["cdylib"]
path       = "src/slash_commands_example.rs"

[dependencies]
zed_extension_api = "0.1.0"

[lints]
workspace = true
