# yaml-language-server: $schema=https://www.schemastore.org/github-issue-config.json
blank_issues_enabled: true
contact_links:
  - name: Our Discord community
    url: https://discord.com/invite/zedindustries
    about: Join our Discord server for real-time discussion and user support.
