[package]
name              = "dev_container"
version           = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace             = true
async-tar.workspace          = true
async-trait.workspace        = true
fs.workspace                 = true
futures.workspace            = true
gpui.workspace               = true
http.workspace               = true
http_client.workspace        = true
log.workspace                = true
menu.workspace               = true
picker.workspace             = true
project.workspace            = true
regex.workspace              = true
serde.workspace              = true
serde_json.workspace         = true
serde_json_lenient.workspace = true
serde_yaml.workspace         = true
settings.workspace           = true
shlex.workspace              = true
ui.workspace                 = true
util.workspace               = true
walkdir.workspace            = true
workspace.workspace          = true
worktree.workspace           = true
yaml-rust2.workspace         = true

[dev-dependencies]
fs                   = { workspace = true, features = ["test-support"] }
gpui                 = { workspace = true, features = ["test-support"] }
indoc.workspace      = true
project              = { workspace = true, features = ["test-support"] }
serde_json.workspace = true
settings             = { workspace = true, features = ["test-support"] }

env_logger.workspace = true
util                 = { workspace = true, features = ["test-support"] }
workspace            = { workspace = true, features = ["test-support"] }
worktree             = { workspace = true, features = ["test-support"] }

[lints]
workspace = true
