[package]
name              = "gpui_shared_string"
version           = "0.1.0"
edition.workspace = true
license           = "Apache-2.0"
publish.workspace = true

[lib]
doctest = false
path    = "gpui_shared_string.rs"
test    = false

[dependencies]
schemars.workspace = true
serde.workspace    = true
smol_str           = "0.3.6"

[lints]
workspace = true
