[package]
name              = "telemetry"
version           = "0.1.0"
edition.workspace = true
license           = "GPL-3.0-or-later"
publish.workspace = true

[lib]
path = "src/telemetry.rs"

[dependencies]
futures.workspace          = true
serde_json.workspace       = true
telemetry_events.workspace = true

[lints]
workspace = true
