[package]
name              = "lmstudio"
version           = "0.1.0"
edition.workspace = true
license           = "GPL-3.0-or-later"
publish.workspace = true

[lib]
path = "src/lmstudio.rs"

[dependencies]
anyhow.workspace      = true
futures.workspace     = true
http_client.workspace = true
schemars              = { workspace = true, optional = true }
serde.workspace       = true
serde_json.workspace  = true

[features]
default  = []
schemars = ["dep:schemars"]

[lints]
workspace = true
