[package]
name              = "bedrock"
version           = "0.1.0"
edition.workspace = true
license           = "GPL-3.0-or-later"
publish.workspace = true

[lib]
path = "src/bedrock.rs"

[dependencies]
anyhow.workspace       = true
aws-sdk-bedrockruntime = { workspace = true, features = ["behavior-version-latest"] }
aws-smithy-types       = { workspace = true }
futures.workspace      = true
schemars               = { workspace = true, optional = true }
serde.workspace        = true
serde_json.workspace   = true
strum.workspace        = true
thiserror.workspace    = true

[features]
default  = []
schemars = ["dep:schemars"]

[lints]
workspace = true
