[package]
name              = "notifications"
version           = "0.1.0"
edition.workspace = true
license           = "GPL-3.0-or-later"
publish.workspace = true

[package.metadata.cargo-shear]
ignored = ["component"]

[lib]
doctest = false
path    = "src/notifications.rs"

[dependencies]
anyhow.workspace       = true
channel.workspace      = true
client.workspace       = true
component.workspace    = true
futures-lite.workspace = true
gpui.workspace         = true
rpc.workspace          = true
sum_tree.workspace     = true
time.workspace         = true
ui.workspace           = true
util.workspace         = true
workspace.workspace    = true
zed_actions.workspace  = true

[dev-dependencies]
client = { workspace = true, features = ["test-support"] }
gpui   = { workspace = true, features = ["test-support"] }
rpc    = { workspace = true, features = ["test-support"] }
util   = { workspace = true, features = ["test-support"] }

[features]
test-support = [
  "channel/test-support",

  "gpui/test-support",
  "rpc/test-support",
]

[lints]
workspace = true
