name: "Check formatting"
description: "Checks code formatting use cargo fmt"
runs: { steps: [{ name: cargo-fmt, run: "cargo fmt --all -- --check", shell: "bash -euxo pipefail {0}" }], using: "composite" }
