name: "Check formatting"
description: "Checks code formatting use cargo fmt"
runs: { steps: [{ run: "cargo fmt --all -- --check", shell: "bash -euxo pipefail {0}" }], name: cargo-fmt, using: "composite" }
